# Generated by Django 3.0.8 on 2020-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startBid',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
