# Generated by Django 3.0.8 on 2020-07-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200713_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
